### ISSUE TITLE
Neue Nutzer in users.properties werden ignoriert

### ISSUE THREAD

**Issue by b4seven** [chboehm/meta-upload#1]
Hallo Robert,

ich habe in die /var/local/ida/users.properties neue Nutzerinnen eingetragen, ich kann mich aber nicht damit anmelden. Auch ein Neustarten des Tomcat hat nicht geholfen.
Fehlt noch irgendwo ein Eintrag?

Danke,
Stefanie

**Comment by rproutermedia** [comment]
Hallo Stefanie,
ich konnte mich gerade mit deinem Account einloggen. Hast du an den BasicAuth-Zugang für die Website gedacht (siehe Wiki)?
Die Institutions-ID der Beispiel-Nutzerin "karin" müsste "genderbib", nicht "Genderbib" heißen (alle Institutions-IDs sind im Wiki oder unter src/main/resources/spring/ida-beans.xml zu finden).

Grüße
Robert

**Comment by b4seven** [comment]
Vielen Dank! Jetzt sehe ich es war mein Fehler...
http://meta-katalog.eu/meta-upload/ statt http://upload.meta-katalog.eu/meta-upload/ aufgerufen :/
